// ============ 跟读句库（带语调/情感提示） ============
const SHADOW_BANK = [
  { en: "Honestly, I'm not upset — I'm just a little disappointed.", zh: "说实话，我没有生气——只是有点失望。", focus: "重音落在 upset 和 disappointed，体会两种情绪的对比" },
  { en: "That sounds amazing! I'd love to join if you don't mind.", zh: "听起来太棒了！如果你不介意的话我很想加入。", focus: "amazing 用上扬语调表达热情" },
  { en: "I see your point, but I'm not sure it would work in our case.", zh: "我明白你的意思，但我不确定这在我们的情况下行得通。", focus: "委婉反对：but 前稍作停顿，语气平缓" },
  { en: "It's been a long day. I just want to curl up on the couch and do nothing.", zh: "今天太累了。我只想窝在沙发上什么都不干。", focus: "疲惫感：整体放慢，nothing 拖长" },
  { en: "Wait, are you serious? That's the best news I've heard all week!", zh: "等等，你是认真的吗？这是我这周听到的最好的消息！", focus: "惊讶+兴奋：serious 上扬，best 重读" },
  { en: "I'm a bit torn. Part of me wants to stay, but part of me thinks it's time to move on.", zh: "我有点纠结。一半想留下，一半又觉得该往前走了。", focus: "矛盾心情：两个 part of me 之间明显停顿" },
  { en: "Could you walk me through your thinking on this?", zh: "你能给我讲讲你在这件事上的思路吗？", focus: "职场礼貌请求：句尾微微上扬" },
  { en: "Let me get back to you on that — I want to double-check the numbers first.", zh: "这个我稍后回复你——我想先核对一下数据。", focus: "自然的职场缓冲语，语速平稳" },
  { en: "To be fair, we didn't have all the information at the time.", zh: "平心而论，我们当时并没有掌握全部信息。", focus: "To be fair 之后停顿半拍" },
  { en: "I can't quite put it into words, but something about this place feels like home.", zh: "我说不太上来，但这个地方总让我有种家的感觉。", focus: "柔和感性的语气，home 轻轻收尾" },
  { en: "No worries at all — these things happen.", zh: "完全没关系——这种事难免的。", focus: "安慰他人：轻松下降调，不要太用力" },
  { en: "If I'm being honest, I think we could have handled it better.", zh: "说实话，我觉得我们本可以处理得更好。", focus: "诚恳反思：honest 和 better 稍重读" },
  { en: "That's a fair point. I hadn't thought about it that way.", zh: "有道理，我之前没从这个角度想过。", focus: "真诚认可：fair point 重读" },
  { en: "I was on the fence for weeks, but I finally made up my mind.", zh: "我犹豫了好几周，最后终于下定了决心。", focus: "叙述节奏：finally 处加重提速" },
  { en: "It's not the end of the world, but it's definitely frustrating.", zh: "虽然不是世界末日，但确实挺让人心烦的。", focus: "先轻描淡写，definitely 转折加重" },
  { en: "Long story short, we missed the deadline, but the client was surprisingly understanding.", zh: "长话短说，我们错过了截止日期，但客户出乎意料地通情达理。", focus: "讲故事节奏：surprisingly 上扬制造转折" },
  { en: "I'd rather we talk it through now than let it become a bigger issue.", zh: "我宁愿我们现在把话说开，也不要让它变成更大的问题。", focus: "坚定但不强硬：rather 和 now 重读" },
  { en: "You know what? Let's just try it and see what happens.", zh: "知道吗？我们就试试看吧，看看会怎样。", focus: "果断轻快：You know what 干脆利落" },
  { en: "I really appreciate you taking the time — it means a lot to me.", zh: "真的很感谢你抽出时间——这对我意义重大。", focus: "真诚感谢：means a lot 放慢加重" },
  { en: "Off the top of my head, I'd say it's a mix of timing and luck.", zh: "不假思索地说，我觉得是时机和运气的结合。", focus: "自然口语开场：整体连贯流畅" },
  { en: "It's bittersweet, honestly. I'm excited for the new chapter, but I'll miss this team.", zh: "说实话挺百感交集的。我期待新篇章，但会想念这个团队。", focus: "复杂情感：bittersweet 慢，excited 扬，miss 沉" },
  { en: "Can we take a step back and look at the bigger picture?", zh: "我们能退一步看看全局吗？", focus: "会议引导语：step back 和 bigger picture 重读" },
  { en: "I didn't see that coming at all — it completely caught me off guard.", zh: "我完全没料到——真是让我措手不及。", focus: "惊讶：at all 上扬，completely 加重" },
  { en: "At the end of the day, what matters is that we learned something from it.", zh: "归根结底，重要的是我们从中学到了东西。", focus: "总结性语气：沉稳的降调收尾" },
  { en: "I hate to say it, but I told you so.", zh: "我不想这么说，但我早就告诉过你了。", focus: "半开玩笑的得意：told you so 拖长" },
  { en: "Take your time — there's no rush at all.", zh: "慢慢来——一点都不急。", focus: "安抚：整体放慢，no rush 轻柔" },
  { en: "I'm not mad, I promise. Just a little tired, that's all.", zh: "我没生气，真的。只是有点累而已。", focus: "疲惫中的温和：promise 稍作停顿" },
  { en: "You did what?! Please tell me you're joking.", zh: "你干了什么？！请告诉我你是在开玩笑。", focus: "夸张惊讶：what 猛地上扬" },
  { en: "Honestly, I couldn't have done it without you.", zh: "说真的，没有你我根本做不到。", focus: "真诚致谢：without you 放慢加重" },
  { en: "It's a long shot, but it might just work.", zh: "希望不大，但没准真能成。", focus: "先压低再点燃希望：might just work 上扬" },
  { en: "I'm so sorry — that completely slipped my mind.", zh: "真对不起——我完全给忘了。", focus: "歉意：sorry 拖长，completely 加重" },
  { en: "Look, I get it. I've been there too.", zh: "听我说，我懂。我也经历过。", focus: "共情：Look 后停顿，语气放软" },
  { en: "Can I be totally honest with you for a second?", zh: "我能跟你说句大实话吗？", focus: "认真转折前的铺垫：honest 重读" },
  { en: "That's exactly what I was trying to say!", zh: "这正是我想说的！", focus: "兴奋认同：exactly 猛加重" },
  { en: "Well, that didn't go the way I expected.", zh: "好吧，这和我预想的完全不一样。", focus: "自嘲：Well 拖长，语调下滑" },
  { en: "Between you and me, I think he's making a huge mistake.", zh: "偷偷跟你说，我觉得他在犯一个大错。", focus: "压低音量的八卦感：huge 加重" },
  { en: "I know it sounds crazy, but hear me out.", zh: "我知道这听起来很疯狂，但听我说完。", focus: "说服：hear me out 一字一顿" },
  { en: "Fair enough. I hadn't looked at it that way.", zh: "有道理。我之前没从这个角度看过。", focus: "让步认可：Fair enough 干脆利落" },
  { en: "Don't get me wrong — I love the idea. I'm just worried about the timing.", zh: "别误会——我很喜欢这个想法，只是担心时机。", focus: "先扬后抑：love 上扬，worried 转沉" },
  { en: "Whatever happens, we'll figure it out together.", zh: "无论发生什么，我们都会一起解决。", focus: "坚定安慰：together 沉稳收尾" },
  { en: "You have no idea how much this means to me.", zh: "你不知道这对我来说意味着什么。", focus: "动情：no idea 放慢，means 加重" },
  { en: "Let's just say it wasn't my finest moment.", zh: "这么说吧，那不是我最光彩的时刻。", focus: "幽默自嘲：finest moment 带笑意" },
  { en: "Hold on — let me make sure I understood you correctly.", zh: "等等——让我确认一下我理解得对不对。", focus: "会议确认：Hold on 果断，后半平稳" },
  { en: "If it were up to me, we'd ship it tomorrow.", zh: "要是我说了算，我们明天就上线。", focus: "虚拟语气：up to me 重读" },
  { en: "The more I think about it, the more it makes sense.", zh: "我越想越觉得有道理。", focus: "递进节奏：两个 more 依次加重" },
  { en: "I was this close to giving up, and then everything changed.", zh: "我差一点就放弃了，然后一切都变了。", focus: "悬念：this close 捏紧，changed 释放" },
  { en: "No pressure, but everyone is counting on you.", zh: "别有压力哈，不过大家都指望你了。", focus: "调侃：No pressure 轻松，counting on you 挑眉感" },
  { en: "It's one of those days when nothing seems to go right.", zh: "今天就是那种什么都不顺的日子。", focus: "无奈：nothing 拖长下沉" },
  { en: "Trust me, you'll thank me later.", zh: "相信我，你以后会感谢我的。", focus: "自信：Trust me 停顿，later 轻快收尾" },
  { en: "I couldn't agree more — you took the words right out of my mouth.", zh: "我完全同意——你说出了我的心声。", focus: "强烈认同：couldn't agree more 饱满" },
  { en: "Something came up, so I'll have to take a rain check.", zh: "我临时有事，只能改天了。", focus: "委婉改期：rain check 轻描淡写" },
  { en: "Off the record, I think the plan needs a lot more work.", zh: "私下说，我觉得这个方案还差得远。", focus: "压低的坦率：a lot more 加重" },
  { en: "It's not that I don't want to help — I just don't know how.", zh: "不是我不想帮——我只是不知道怎么帮。", focus: "澄清：not 和 how 两处重音" },
  { en: "Give me a second to wrap my head around this.", zh: "给我点时间消化一下这个信息。", focus: "思考中：语速放慢，this 收尾" },
  { en: "You're kidding me. After everything we did?", zh: "开什么玩笑。我们做了这么多之后？", focus: "失望+难以置信：everything 拖长上扬" },
  { en: "Say what you will, but the results speak for themselves.", zh: "随你怎么说，但结果说明了一切。", focus: "自信反驳：results 加重" },
  { en: "I'm all ears — walk me through what happened.", zh: "我洗耳恭听——跟我讲讲发生了什么。", focus: "倾听姿态：all ears 温和上扬" },
  { en: "That was hands down the best decision I've ever made.", zh: "那绝对是我做过的最好的决定。", focus: "强调：hands down 一字一顿" },
  { en: "Deep breath. We've handled worse than this.", zh: "深呼吸。比这更糟的我们都处理过。", focus: "冷静安抚：短句之间明显停顿" },
  { en: "How did it go? I've been dying to hear about it.", zh: "怎么样？我一直特别想听你说呢。", focus: "好奇期待：dying 夸张拖长" },
  { en: "Sorry, I didn't catch that — could you say it one more time?", zh: "抱歉我没听清——你能再说一遍吗？", focus: "沟通修复：catch that 轻，请求句尾上扬" },
  { en: "Correct me if I'm wrong, but didn't we meet somewhere before?", zh: "如果我记错了请纠正，但我们是不是在哪儿见过？", focus: "试探回忆：before 上扬" },
  { en: "To be honest, I'd rather stay in tonight. Would you hate me if I bailed?", zh: "说实话我今晚想宅在家。我放鸽子你会恨我吗？", focus: "委婉取消：bailed 带笑意" },
  { en: "That's so kind of you, but I really couldn't accept this.", zh: "你太好了，但这个我真的不能收。", focus: "礼貌推辞：really 加重，语气真诚" },
  { en: "You should've seen his face — it was absolutely priceless.", zh: "你真该看看他的表情——简直绝了。", focus: "讲八卦的兴奋：priceless 拖长" },
  { en: "I'll be honest with you: it's not perfect, but it's a solid start.", zh: "跟你说实话：它不完美，但是个扎实的开始。", focus: "平衡评价：not perfect 沉，solid start 扬" },
  { en: "Whatever you decide, I've got your back.", zh: "无论你怎么决定，我都挺你。", focus: "支持：got your back 坚定收尾" },
  { en: "Is it just me, or is it freezing in here?", zh: "是我的错觉吗，还是这里真的冷得要命？", focus: "征求共鸣：just me 上扬，freezing 夸张" },
  { en: "I could've sworn I left my keys right here.", zh: "我发誓钥匙刚才就放在这儿的。", focus: "困惑：sworn 加重，right here 一字一顿" },
  { en: "Now that you mention it, I did notice something odd.", zh: "你这么一说，我确实注意到有点不对劲。", focus: "恍然：did 重读表强调" },
  { en: "Don't take this the wrong way, but I think you deserve better.", zh: "别误会我的意思，但我觉得你值得更好的。", focus: "谨慎直言：前半快后半慢" },
  { en: "It's a small world — of all places, I ran into her in Tokyo.", zh: "世界真小——偏偏在东京碰到了她。", focus: "感叹巧合：of all places 加重" },
  { en: "If worse comes to worst, we can always start over.", zh: "大不了从头再来。", focus: "兜底安慰：always 平稳有力" },
  { en: "I'm flattered, honestly, but I'll have to think about it.", zh: "真的很荣幸，但我得考虑考虑。", focus: "受宠若惊+缓冲：flattered 上扬，后半放缓" },
  { en: "Believe it or not, this whole thing started as a joke.", zh: "信不信由你，这整件事一开始只是个玩笑。", focus: "故事开头：Believe it or not 抓注意力" },
  { en: "There's no easy way to say this, so I'll just say it.", zh: "这话怎么说都难开口，所以我就直说了。", focus: "坏消息铺垫：整体放慢，just say it 果断" },
  { en: "You're telling me she planned all of this by herself?", zh: "你是说这一切都是她一个人策划的？", focus: "难以置信：all of this 加重，句尾高扬" },
  { en: "I wouldn't miss it for the world.", zh: "说什么我也不会错过。", focus: "强烈承诺：for the world 饱满收尾" },
  { en: "Let's agree to disagree and enjoy the dinner, shall we?", zh: "我们保留各自意见，好好吃饭，行吗？", focus: "化解争论：shall we 轻快上扬" },
  { en: "It's on the tip of my tongue — give me a second.", zh: "话就在嘴边——等我一下。", focus: "话到嘴边：tip of my tongue 连读" },
  { en: "The way I see it, we've got nothing to lose.", zh: "依我看，我们没什么可失去的。", focus: "乐观分析：nothing 加重" },
  { en: "Not gonna lie, I was a nervous wreck before the interview.", zh: "不骗你，面试前我紧张得一塌糊涂。", focus: "坦白：Not gonna lie 口语连读" },
  { en: "Take it with a grain of salt, but I heard the team might be restructured.", zh: "别全信哈，但我听说团队可能要重组。", focus: "传闻提醒：grain of salt 轻，restructured 压低" },
  { en: "You can say that again — this line is taking forever.", zh: "可不是嘛——这队排得也太久了。", focus: "抱怨附和：forever 夸张拖长" },
  { en: "For the record, I was against this idea from day one.", zh: "郑重声明，我从第一天起就反对这个主意。", focus: "撇清声明：For the record 停顿，day one 加重" },
  { en: "It's a blessing in disguise, if you ask me.", zh: "要我说，这是因祸得福。", focus: "宽慰：blessing 上扬" },
  { en: "I'm not in the mood, but thanks for asking.", zh: "我现在没心情，不过谢谢你问我。", focus: "低落但礼貌：前半低沉，thanks 回暖" },
  { en: "Suit yourself — just don't say I didn't warn you.", zh: "随你便——别说我没提醒过你。", focus: "随你便：Suit yourself 耸肩感" },
  { en: "Come to think of it, I haven't taken a real vacation in two years.", zh: "仔细一想，我两年没休过真正的假了。", focus: "反应过来：Come to think of it 若有所思" },
  { en: "You had me at 'free food' — count me in.", zh: "你说到'免费吃的'我就已经答应了——算我一个。", focus: "幽默爽快：free food 加重带笑" },
  { en: "Easier said than done, but I'll give it my best shot.", zh: "说来容易做来难，但我会全力以赴。", focus: "认清难度仍应承：best shot 坚定" },
  { en: "That explains a lot, actually.", zh: "这就说得通了。", focus: "恍然大悟：explains 重读，actually 收尾" },
  { en: "I hate to break it to you, but the tickets sold out an hour ago.", zh: "我也不想告诉你这个，但票一小时前就卖光了。", focus: "委婉坏消息：hate 拖长，sold out 清晰" },
  { en: "No offense, but I think we're overcomplicating this.", zh: "无意冒犯，但我觉得我们把事情搞复杂了。", focus: "直言：No offense 停顿再继续" },
  { en: "None taken — you're probably right.", zh: "没事——你可能是对的。", focus: "大度回应：None taken 轻松" },
  { en: "Word on the street is they're opening a new branch downtown.", zh: "小道消息说他们要在市中心开新分店。", focus: "八卦语气：Word on the street 压低神秘" },
  { en: "I'm torn, but if you twisted my arm, I'd pick the beach.", zh: "我很纠结，但非要我选的话，我选海边。", focus: "半推半就：twisted my arm 俏皮" },
  { en: "Well, look who finally decided to show up!", zh: "哟，看看谁终于舍得露面了！", focus: "打趣迟到：finally 夸张拖长" },
  { en: "Give credit where it's due — she pulled the whole event off.", zh: "该表扬就得表扬——整场活动是她一手办成的。", focus: "公道称赞：pulled it off 加重" },
  { en: "So, long story short, that's why I never order oysters anymore.", zh: "所以长话短说，这就是我再也不点生蚝的原因。", focus: "故事收尾：never 加重，anymore 带笑收尾" },
];

// ============ 话题卡库 ============
const TOPICS = {
  daily: {
    label: "日常生活",
    items: [
      { q: "What does your typical morning look like? Is there anything you'd like to change about it?", zh: "你典型的早晨是什么样的？有什么想改变的吗？", hints: ["The first thing I do is...", "I tend to...", "If I could, I'd..."] },
      { q: "Describe your perfect weekend, from Friday night to Sunday evening.", zh: "描述你完美的周末，从周五晚到周日晚。", hints: ["I'd kick things off with...", "Ideally, ...", "To wrap up the weekend, ..."] },
      { q: "Talk about a place in your city you always take visitors to. Why there?", zh: "聊聊你总带外地朋友去的地方，为什么是那里？", hints: ["Whenever friends visit, I...", "What makes it special is...", "You can't leave without..."] },
      { q: "What's a small thing that instantly improves your mood?", zh: "什么小事能瞬间让你心情变好？", hints: ["It never fails to...", "The moment I..., I feel...", "It's a little thing, but..."] },
      { q: "Tell me about your best friend. How did you meet, and what makes the friendship work?", zh: "聊聊你最好的朋友：怎么认识的？友谊为何长久？", hints: ["We go way back to...", "What keeps us close is...", "We just click because..."] },
      { q: "What's your relationship with your phone? Is it healthy?", zh: "你和手机的关系健康吗？", hints: ["I catch myself...", "I've been trying to cut down on...", "The tricky part is..."] },
      { q: "Describe a meal you could eat every day for the rest of your life.", zh: "描述一顿你可以吃一辈子的饭。", hints: ["I never get tired of...", "The texture is..., and the flavor is...", "It reminds me of..."] },
      { q: "Talk about a habit you've built or broken, and how you did it.", zh: "聊聊你养成或戒掉的一个习惯，你是怎么做到的？", hints: ["It took me ... to...", "The turning point was...", "What worked for me was..."] },
      { q: "What do you usually do when you can't fall asleep?", zh: "睡不着的时候你一般会做什么？", hints: ["My go-to is...", "Sometimes it backfires because...", "Nine times out of ten, ..."] },
      { q: "Describe the last time you laughed really hard. What happened?", zh: "描述你上次笑到不行的经历。", hints: ["So there we were...", "Out of nowhere, ...", "I couldn't stop laughing because..."] },
      { q: "If you had a completely free day tomorrow, how would you spend it?", zh: "如果明天完全自由，你会怎么过？", hints: ["First thing in the morning, I'd...", "I'd treat myself to...", "No plans, just..."] },
      { q: "Talk about something you bought recently that turned out great — or terrible.", zh: "聊聊你最近买的一个特值（或特坑）的东西。", hints: ["It turned out to be...", "Totally worth it because...", "If I could return it, I..."] },
      { q: "How do you usually celebrate special occasions with family or friends?", zh: "你们家人朋友之间怎么庆祝特殊日子？", hints: ["It's kind of a tradition to...", "We always make a point of...", "What matters most is..."] },
      { q: "What's a skill you'd love to learn just for fun, and why?", zh: "有什么纯粹为了好玩想学的技能？", hints: ["I've always been curious about...", "Just for the fun of it, ...", "I picture myself..."] },
      { q: "Describe your neighborhood to someone who has never been there.", zh: "向没来过的人描述你住的街区。", hints: ["It's the kind of place where...", "Right around the corner, there's...", "What I love about it is..."] },
      { q: "Do you prefer detailed plans or spontaneity when traveling? Tell a story that proves it.", zh: "旅行时你喜欢做攻略还是随性？讲个能证明的故事。", hints: ["I'm the type who...", "One time, we ended up...", "Looking back, ..."] },
      { q: "What's something you do differently from most people around you?", zh: "你有什么和周围大多数人不一样的做法？", hints: ["Unlike most people, I...", "People find it odd that...", "It works for me because..."] },
      { q: "Talk about a movie or show you recommend to everyone. What makes it so good?", zh: "聊聊你逢人就推荐的电影或剧，好在哪里？", hints: ["I can't recommend it enough.", "What sets it apart is...", "By the end, you'll..."] },
      { q: "Are you a morning person or a night owl? How does it shape your day?", zh: "你是早起型还是夜猫子？这如何影响你的一天？", hints: ["I'm definitely more of a...", "My brain doesn't switch on until...", "If I could redesign my schedule, ..."] },
      { q: "Talk about a food you hated as a kid but love now.", zh: "聊聊一种你小时候讨厌、现在却喜欢的食物。", hints: ["I used to push it around my plate.", "Somewhere along the way, ...", "Now I actually crave it."] },
      { q: "What's your relationship with exercise? Love it, hate it, or complicated?", zh: "你和运动的关系如何？热爱、讨厌，还是一言难尽？", hints: ["It's complicated, honestly.", "I always feel better afterwards, but...", "What keeps me going is..."] },
      { q: "Where do you go when you need to clear your head?", zh: "你需要理清思绪时会去哪里？", hints: ["Whenever things get overwhelming, I...", "There's something about ... that calms me down.", "By the time I leave, ..."] },
      { q: "How do you like to spend time alone? Do you need much of it?", zh: "你喜欢怎么独处？你需要很多独处时间吗？", hints: ["I recharge by...", "Too much company drains me / I get restless when...", "My favorite solo activity is..."] },
      { q: "Do you have pets, or would you want one? Talk about animals in your life.", zh: "你养宠物吗？想养吗？聊聊你生活中的动物。", hints: ["I've always been a ... person.", "The best part is coming home to...", "The downside, of course, is..."] },
      { q: "Share a small win from this week — anything counts.", zh: "分享本周的一个小胜利——任何事都算。", hints: ["It might sound tiny, but...", "I finally got around to...", "It made my whole day because..."] },
      { q: "What are you saving up for right now, and why that?", zh: "你现在在为什么攒钱？为什么是它？", hints: ["I've been setting aside money for...", "It's a big purchase, so...", "The way I see it, it's an investment in..."] },
      { q: "Describe a tradition from your hometown that outsiders might find interesting.", zh: "描述你家乡一个外地人可能觉得有意思的传统。", hints: ["Every year around..., we...", "The whole point of it is...", "Even now, whenever I..., it takes me back."] },
      { q: "What's the best gift you've ever given or received? What made it special?", zh: "你送过或收过的最好的礼物是什么？特别在哪里？", hints: ["It wasn't expensive, but...", "What made it special was the thought behind it.", "I still keep it because..."] },
      { q: "When you make big decisions, do you trust your gut or make pro-con lists?", zh: "做重大决定时，你靠直觉还是列利弊清单？", hints: ["Nine times out of ten, I...", "My gut has never let me down / has burned me before.", "For the really big stuff, ..."] },
      { q: "City center, suburbs, or countryside — where would you actually thrive?", zh: "市中心、郊区还是乡村——你在哪里才能过得最好？", hints: ["I'm torn between the energy of ... and the calm of ...", "What I couldn't live without is...", "Maybe the ideal is..."] },
      { q: "Describe your social media habits. Are you happy with them?", zh: "描述你的社交媒体使用习惯，你对它们满意吗？", hints: ["I catch myself doomscrolling when...", "I've tried to cut back by...", "Honestly, the one app I can't quit is..."] },
      { q: "Is there a song that instantly takes you back to a specific time in your life?", zh: "有没有一首歌能瞬间把你带回人生的某个时刻？", hints: ["The second it comes on, I'm back in...", "It was the soundtrack of that whole...", "Even now, I get goosebumps when..."] },
      { q: "Describe your dream home in detail — location, layout, the little things.", zh: "详细描述你的梦想之家——位置、格局和那些小细节。", hints: ["The non-negotiable for me is...", "Picture this: ...", "It's less about size and more about..."] },
      { q: "Tell me about a time a stranger was unexpectedly kind to you.", zh: "讲讲一次陌生人对你意外友善的经历。", hints: ["Out of nowhere, this person...", "They didn't have to, but...", "It restored my faith in..."] },
      { q: "Describe your daily commute. How do you make the time useful or bearable?", zh: "描述你的日常通勤，你如何让这段时间有用或不那么难熬？", hints: ["Door to door, it takes about...", "I've turned it into my ... time.", "The worst part is..., but..."] },
      { q: "Which season suits you best, and what do you do differently in it?", zh: "哪个季节最适合你？你在那个季节会做些什么不同的事？", hints: ["I come alive in...", "There's a ritual I have every...", "The light / the air / the food is just..."] },
      { q: "A friend has 48 hours in your hometown. Plan their itinerary out loud.", zh: "朋友在你家乡只待 48 小时，口头帮 TA 规划行程。", hints: ["First things first, I'd take them to...", "You can't understand this city until you've...", "We'd wrap up the trip with..."] },
      { q: "Do you collect anything — or did you as a kid? Tell the story.", zh: "你收藏什么东西吗？或者小时候收藏过？讲讲这个故事。", hints: ["It started when someone gave me...", "At my peak, I had...", "Looking back, it was really about..."] },
      { q: "How do you unwind after a genuinely stressful day?", zh: "度过真正高压的一天后，你如何放松下来？", hints: ["The first thing I do when I get home is...", "It doesn't fully work unless...", "By the end of the evening, I..."] },
      { q: "What's something you do just for yourself, not to share or show anyone?", zh: "有什么事你纯粹为自己做，不为分享也不为展示？", hints: ["Nobody really knows I...", "It's my way of...", "If I skip it for a week, I..."] },
      { q: "What's in your bag or backpack right now? Any items with a story?", zh: "你的包里现在装着什么？有没有什么东西背后有故事？", hints: ["I never leave home without...", "There's this one thing I keep 'just in case'...", "Funny enough, the oldest thing in there is..."] },
      { q: "Describe your go-to drink order and the ritual around it.", zh: "描述你固定的饮品选择和围绕它的小仪式。", hints: ["My usual is..., no..., extra...", "The first sip always...", "I judge a café by..."] },
      { q: "Talk about a hobby you dropped. Would you ever pick it back up?", zh: "聊聊一个你放弃了的爱好，你会重拾它吗？", hints: ["I used to be really into...", "Life got in the way when...", "Every now and then I'm tempted to..."] },
      { q: "When you get sick, do you rest properly or push through? Tell a story.", zh: "生病时你会好好休息还是硬扛？讲个例子。", hints: ["I'm terrible at being sick because...", "Last time, I insisted on... and paid for it.", "My recovery routine is..."] },
      { q: "Describe your haircut experiences. How do you explain what you want?", zh: "聊聊你的理发经历，你怎么描述自己想要的发型？", hints: ["I always say 'just a trim' and then...", "The awkward part is the small talk about...", "Once, the result was so ... that I..."] },
      { q: "Rate your own cooking honestly. What's your signature dish?", zh: "诚实评价你的厨艺，你的拿手菜是什么？", hints: ["On a scale of one to ten, I'm a...", "The one dish I can nail every time is...", "My biggest kitchen disaster was..."] },
      { q: "Which three apps could you genuinely not live without? Rank them.", zh: "哪三个 App 你真的离不开？排个序。", hints: ["Number one, hands down, is...", "It's embarrassing, but I check ... before I even...", "If I had to give one up, ..."] },
      { q: "What part of being an adult surprised you the most?", zh: "成年生活中哪部分最让你意外？", hints: ["Nobody warned me about...", "I thought adults had it figured out, but...", "The weirdest part is suddenly caring about..."] },
      { q: "How has your sleep been lately? What helps or ruins it?", zh: "你最近睡眠怎么样？什么帮助或毁掉你的睡眠？", hints: ["My sleep has been all over the place because...", "The one thing that reliably knocks me out is...", "I know I shouldn't ... before bed, but..."] },
      { q: "What's your favorite holiday of the year, and how do you spend it?", zh: "你最喜欢一年中的哪个节日？怎么过？", hints: ["It's the one time of year when...", "The build-up is almost better than...", "My favorite memory of it is..."] },
      { q: "Talk about something under 100 yuan that genuinely improved your life.", zh: "聊聊一件不到 100 块却真正改善你生活的东西。", hints: ["Best money I've ever spent, honestly.", "I use it literally every day for...", "I've recommended it to..."] },
      { q: "Open your photo gallery. What do you photograph the most, and why?", zh: "打开你的相册，你拍得最多的是什么？为什么？", hints: ["My camera roll is basically 90%...", "I have a whole album just for...", "Looking back at them makes me..."] },
      { q: "Describe your perfect rainy day at home.", zh: "描述你完美的居家雨天。", hints: ["The sound of rain instantly makes me want to...", "I'd make a big pot of...", "There's something cozy about..."] },
      { q: "What's your relationship with driving and public transport?", zh: "你和开车/公共交通的关系如何？", hints: ["I'm the kind of person who...", "Rush hour brings out my...", "If the city improved one thing, ..."] },
      { q: "Do you play any games — video, board, or mobile? What's the appeal?", zh: "你玩游戏吗——主机、桌游还是手游？吸引你的是什么？", hints: ["My comfort game is...", "I'm weirdly competitive about...", "What hooks me is the feeling of..."] },
      { q: "If you opened a little shop or café, what would it be like?", zh: "如果你开一家小店或咖啡馆，它会是什么样？", hints: ["Picture a tiny place that...", "The signature item would be...", "I'd want regulars who..."] },
      { q: "What everyday task do you always put off, and what's your excuse?", zh: "日常生活中你总拖着不做的事是什么？借口是什么？", hints: ["I will do literally anything to avoid...", "My go-to excuse is...", "When I finally do it, it takes five minutes and I..."] },
      { q: "Are you a grocery list person or an impulse buyer? Walk me through a typical trip.", zh: "你买菜购物列清单还是随性买？描述一次典型的购物。", hints: ["I walk in for one thing and leave with...", "My weakness is the ... aisle.", "By the checkout, my cart is..."] },
      { q: "Describe the view from your window and what it makes you think about.", zh: "描述你窗外的景色，以及它让你想到什么。", hints: ["Right now, I can see...", "At night, it turns into...", "I've watched ... change over the seasons."] },
      { q: "What smell or sound instantly means 'home' to you?", zh: "什么气味或声音会让你瞬间想到'家'？", hints: ["The second I smell..., I'm back in...", "It's oddly specific, but...", "No matter where I live, ... will always mean home."] },
    ],
  },
  work: {
    label: "工作职场",
    items: [
      { q: "Introduce yourself and what you do, as if we just met at a conference.", zh: "像在会议上初识一样，介绍你自己和你的工作。", hints: ["I work on..., which basically means...", "My day-to-day involves...", "What I enjoy most about it is..."] },
      { q: "Walk me through a project you're proud of. What was your role and the result?", zh: "介绍一个你自豪的项目：你的角色和成果。", hints: ["The goal was to...", "I was in charge of...", "In the end, we managed to..."] },
      { q: "Describe a time you disagreed with a colleague or manager. How did you handle it?", zh: "描述一次你和同事/上级意见不合的经历，你怎么处理的？", hints: ["I saw where they were coming from, but...", "Instead of pushing back right away, I...", "We ended up meeting in the middle."] },
      { q: "How do you organize your work when everything feels urgent?", zh: "当所有事都很急时，你怎么安排工作？", hints: ["I start by sorting out...", "My rule of thumb is...", "If push comes to shove, I..."] },
      { q: "Explain something technical from your job to a complete beginner.", zh: "把你工作中的一个技术概念讲给完全的外行听。", hints: ["Think of it like...", "In plain English, it means...", "The reason it matters is..."] },
      { q: "Tell me about a piece of feedback that changed how you work.", zh: "聊聊一条改变了你工作方式的反馈。", hints: ["At first, it stung, but...", "It made me realize...", "Since then, I've made a point of..."] },
      { q: "Describe your ideal team culture. What does a great team feel like day to day?", zh: "描述你理想中的团队文化，好团队日常是什么感觉？", hints: ["People feel safe to...", "There's a healthy amount of...", "What kills a team is..."] },
      { q: "You need to push back on an unrealistic deadline. What do you say to your manager?", zh: "你需要对不现实的截止日期说不，你会怎么和上级说？", hints: ["I want to flag a risk early...", "Realistically, what we can deliver by then is...", "Could we either extend... or cut...?"] },
      { q: "Talk about a mistake you made at work and what you learned from it.", zh: "聊聊你在工作中犯过的一个错误和学到的东西。", hints: ["In hindsight, I should have...", "I owned up to it and...", "The takeaway for me was..."] },
      { q: "How would you convince your team to adopt a new tool or process you believe in?", zh: "你会如何说服团队采用你看好的新工具或新流程？", hints: ["The pain point it solves is...", "We could pilot it on...", "Worst case, we just roll back."] },
      { q: "Describe a typical meeting at your company. What would make meetings better?", zh: "描述你们公司典型的会议，怎样能开得更好？", hints: ["More often than not, ...", "Half the time, we end up...", "Meetings would improve if..."] },
      { q: "Tell me about a time you had to deliver bad news at work.", zh: "聊聊你在工作中传达坏消息的一次经历。", hints: ["I didn't sugarcoat it, but...", "I led with the facts...", "What softened it was..."] },
      { q: "What part of your job would you happily hand over to AI, and what part never?", zh: "工作中哪部分你乐意交给 AI，哪部分绝不？", hints: ["I'd gladly offload...", "Where humans are irreplaceable is...", "It comes down to judgment."] },
      { q: "Where do you want to be professionally in three years? What's the first step?", zh: "三年后你希望职业上到什么位置？第一步是什么？", hints: ["Ideally, I'll have moved into...", "The gap I need to close is...", "The first concrete step is..."] },
      { q: "Give a 60-second project update to a busy executive.", zh: "给一位很忙的高管做 60 秒项目汇报。", hints: ["Bottom line up front: ...", "We're on track / behind on...", "What I need from you is..."] },
      { q: "Describe working with someone whose style was very different from yours.", zh: "描述和一位风格迥异的同事共事的经历。", hints: ["We clashed at first over...", "What I learned to appreciate was...", "We found a rhythm by..."] },
      { q: "What makes someone a great manager, in your experience?", zh: "以你的经验，好的管理者是什么样的？", hints: ["The best manager I've had would...", "It's less about... and more about...", "A red flag is..."] },
      { q: "Practice a job interview answer: 'Tell me about yourself.'", zh: "练习面试题：请介绍一下你自己。", hints: ["I've spent the last ... years...", "What draws me to this role is...", "Outside of work, I..."] },
      { q: "Remote, hybrid, or full-time office — what actually works for you, and why?", zh: "远程、混合还是坐班——哪种真正适合你？为什么？", hints: ["I'm most productive when...", "What people underestimate about remote work is...", "The ideal setup for me would be..."] },
      { q: "A teammate keeps missing deadlines and it's affecting you. What do you do?", zh: "一位队友总是错过截止日期并影响到你，你会怎么做？", hints: ["Before jumping to conclusions, I'd...", "I'd frame it as..., not...", "If nothing changed, I'd have to..."] },
      { q: "Interview question: 'Tell me about a time you failed.'", zh: "面试题：讲一次你失败的经历。", hints: ["The project fell apart because...", "My share of the blame was...", "What I do differently now is..."] },
      { q: "You believe you deserve a raise. Make your case to your manager.", zh: "你认为自己该加薪了，向你的上级陈述理由。", hints: ["Over the past year, I've taken on...", "Based on the market and my scope, ...", "What would it take to get there?"] },
      { q: "Tell me about your first job ever and what it taught you.", zh: "聊聊你人生第一份工作和它教会你的东西。", hints: ["My very first job was...", "It paid next to nothing, but...", "It taught me the value of..."] },
      { q: "What makes a one-on-one with your manager actually useful?", zh: "怎样的一对一沟通才真正有用？", hints: ["The worst 1:1s are just status updates.", "I try to bring up...", "A great manager uses that time to..."] },
      { q: "A new teammate joins tomorrow. Give them the honest orientation speech.", zh: "明天有新同事入职，给 TA 来一段真诚的入职介绍。", hints: ["Officially..., but between us...", "The person you want to know is...", "My biggest tip: don't be afraid to..."] },
      { q: "Describe a time you had to learn something completely new, fast.", zh: "描述一次你必须快速学会全新东西的经历。", hints: ["I was thrown into the deep end when...", "My crash course was basically...", "Within a few weeks, I could..."] },
      { q: "The project keeps growing beyond the original plan. How do you push back?", zh: "项目范围不断膨胀超出原计划，你如何叫停？", hints: ["I'd flag that we're drifting from...", "Every new request costs us...", "Let's park these ideas for phase two."] },
      { q: "What does 'taking ownership' actually look like, day to day?", zh: "'负责到底'在日常工作中具体是什么样的？", hints: ["It's the difference between ... and ...", "Owners don't wait to be told to...", "A small example from my own work: ..."] },
      { q: "Describe your industry to a college student who's considering joining it.", zh: "向一位考虑入行的大学生介绍你所在的行业。", hints: ["The textbook version is..., but the reality is...", "The part nobody tells you is...", "If you love..., you'll thrive; if not..."] },
      { q: "If you could fix one process or tool at work tomorrow, what would it be?", zh: "如果明天就能修好公司里的一个流程或工具，你会选哪个？", hints: ["The thing that drives everyone crazy is...", "We waste hours every week on...", "A simple fix would be..."] },
      { q: "A peer's work has a serious problem. How do you tell them?", zh: "同事的工作有严重问题，你怎么开口？", hints: ["I'd start by asking, not telling: ...", "I'd keep it about the work, not the person.", "Something like: 'I noticed..., can we look at it together?'"] },
      { q: "Walk me through how you prepare for a high-stakes presentation.", zh: "讲讲你如何准备一场重要的演讲或汇报。", hints: ["It starts days before, with...", "I rehearse out loud until...", "Right before going on, I..."] },
      { q: "Work-life balance: describe your reality versus your ideal.", zh: "工作与生活的平衡：你的现状 vs 理想状态。", hints: ["On paper..., but in practice...", "The line gets blurry when...", "One boundary I'm trying to hold is..."] },
      { q: "Tell the story of a meeting that went completely off the rails.", zh: "讲一次彻底跑偏失控的会议。", hints: ["It was supposed to be a quick sync about...", "Twenty minutes in, somehow we were arguing about...", "The lesson: never schedule ... without..."] },
      { q: "Interview question: 'Why are you leaving your current job?'", zh: "面试题：你为什么想离开现在的工作？", hints: ["I've grown a lot there, and now...", "I'm looking for more exposure to...", "It's less about leaving and more about..."] },
      { q: "Interview question: 'What's your greatest strength and biggest weakness?'", zh: "面试题：你最大的优点和缺点是什么？", hints: ["Colleagues would probably say I...", "My weakness used to be..., so I've been...", "A concrete example of that is..."] },
      { q: "Describe a great cross-team collaboration you were part of. Why did it work?", zh: "描述一次成功的跨团队合作，它为什么能成？", hints: ["Usually these things stall because..., but this time...", "What made the difference was...", "We shipped ... that neither team could have alone."] },
      { q: "How is AI changing your field, and how are you adapting?", zh: "AI 正在如何改变你的领域？你如何应对？", hints: ["The tasks disappearing first are...", "Where humans still clearly win is...", "Personally, I've started to..."] },
      { q: "What would make you happily stay at one company for ten years?", zh: "什么条件能让你心甘情愿在一家公司待十年？", hints: ["It comes down to three things: ...", "I'd need to still be growing, meaning...", "Deal-breakers would be..."] },
      { q: "A friend at another company is burning out. What do you tell them?", zh: "别家公司的朋友快熬垮了，你会对 TA 说什么？", hints: ["First, I'd remind them that...", "No job is worth...", "Concretely, I'd suggest they start by..."] },
      { q: "Describe your dream workspace setup, down to the details.", zh: "细致描述你梦想中的办公环境。", hints: ["The non-negotiables are...", "Lighting-wise / chair-wise, I'd want...", "The vibe should feel more like ... than ..."] },
      { q: "How do you say 'I don't know' at work without losing credibility?", zh: "在职场上如何得体地说'我不知道'？", hints: ["I don't have that on hand, but I can find out by...", "My honest read is..., though I'd want to verify...", "Good question — let me check with..."] },
      { q: "Tell me about a time you had to present or speak with zero preparation.", zh: "讲一次你毫无准备就得上台发言的经历。", hints: ["They turned to me and said 'you're up' and I...", "I bought time by...", "Weirdly, it went ... because..."] },
      { q: "Your company adopts a 4-day work week tomorrow. How does your work change?", zh: "公司明天开始四天工作制，你的工作会怎么变？", hints: ["The first thing to die would be...", "We'd have to get ruthless about...", "With the extra day, I'd actually..."] },
      { q: "Describe lunch culture at your workplace. Eat together, alone, at your desk?", zh: "描述你们公司的午餐文化：一起吃、独自吃还是工位吃？", hints: ["The unwritten rule is...", "Lunch is when the real ... happens.", "Personally, I use that hour to..."] },
      { q: "Do you get the 'Sunday scaries'? How do you face Monday mornings?", zh: "你有'周日焦虑'吗？你如何面对周一早晨？", hints: ["Around Sunday evening, I start to...", "What actually helps is...", "By Monday 10 a.m., it's usually..."] },
      { q: "Teach a junior colleague how to write a clear work email.", zh: "教一位新人同事如何写一封清晰的工作邮件。", hints: ["Subject line first: it should...", "Lead with the ask, not the backstory.", "Before hitting send, always check..."] },
      { q: "What are the 'green flags' you look for when interviewing at a company?", zh: "面试一家公司时，你眼中的'加分信号'是什么？", hints: ["A huge green flag is when the interviewer...", "I always ask ... and listen for...", "Red flags aside, what really sells me is..."] },
      { q: "Practice small talk with a foreign colleague in the two minutes before a meeting starts.", zh: "练习会议开始前和外国同事的两分钟寒暄。", hints: ["How's your week going so far?", "Did you do anything fun over the weekend?", "How are you finding the weather / the city?"] },
      { q: "How does your team celebrate wins? Should there be more of it?", zh: "你们团队怎么庆祝成功？应该更多一些吗？", hints: ["Right now, a win usually just means...", "The best celebration we ever had was...", "Even a small ritual like ... would..."] },
      { q: "Describe a manager's mistake you'd never repeat if you were promoted.", zh: "描述一个你若升职绝不会重蹈的管理错误。", hints: ["I once had a manager who...", "The damage wasn't obvious at first, but...", "In their shoes, I would have..."] },
      { q: "How do you protect your focus from interruptions and context switching?", zh: "你如何保护专注力，应对干扰和任务切换？", hints: ["My focus is gone the moment...", "I've started blocking time for...", "The hardest part is saying no to..."] },
      { q: "Which perks genuinely matter more to you than a higher salary?", zh: "哪些福利对你来说真的比更高的薪水重要？", hints: ["I'd trade a raise for ... any day.", "People underrate ... until they lose it.", "The perk that keeps me loyal is..."] },
      { q: "Walk me through your typical workday, hour by hour.", zh: "按时间线介绍你典型的工作日。", hints: ["My day starts properly at...", "The golden hours for deep work are...", "By late afternoon, I'm usually..."] },
      { q: "How do you voice disagreement in a meeting full of people senior to you?", zh: "在满屋子都是前辈的会议上，你如何表达不同意见？", hints: ["I'd frame it as a question first: ...", "Something like: 'building on that, one risk I see is...'", "If it lands badly, I..."] },
      { q: "What skill from a hobby unexpectedly helps you at work?", zh: "哪个来自爱好的技能意外地帮助了你的工作？", hints: ["Weirdly enough, ... taught me...", "It shows up at work whenever I...", "Colleagues are always surprised that I..."] },
      { q: "How do you keep in touch with old colleagues without it feeling forced?", zh: "你如何自然地和老同事保持联系？", hints: ["My trick is to reach out when I see...", "It's less awkward if you lead with...", "Twice a year, I make a point of..."] },
      { q: "If you started a company tomorrow, what would it do and who's your first hire?", zh: "如果明天创业，你做什么？第一个招谁？", hints: ["The gap I keep noticing in the market is...", "Day one, the product would just...", "My first hire has to be someone who..."] },
      { q: "What does a genuinely productive day look like for you — not just a busy one?", zh: "对你来说，真正高效的一天（而非忙碌的一天）长什么样？", hints: ["Busy is when...; productive is when...", "If I moved ... forward even a little, it counts.", "The test I use at 6 p.m. is..."] },
      { q: "Give honest advice to a fresh graduate joining your industry this year.", zh: "给今年入行的应届生一些真诚的建议。", hints: ["Forget what the textbooks said about...", "Your first year is really about...", "The single habit that will set you apart is..."] },
    ],
  },
  deep: {
    label: "深度表达",
    items: [
      { q: "What's a belief you've changed your mind about in recent years? What changed it?", zh: "近几年你改变了什么看法？是什么改变了它？", hints: ["I used to be convinced that...", "What shifted my thinking was...", "Now I'd say it's more nuanced: ..."] },
      { q: "Talk about a moment that genuinely changed how you see the world.", zh: "聊聊一个真正改变你世界观的时刻。", hints: ["Up until then, I had assumed...", "It hit me that...", "Ever since, I..."] },
      { q: "What does success mean to you now, compared to five years ago?", zh: "和五年前相比，现在的你如何定义成功？", hints: ["Five years ago, it was all about...", "These days, I care more about...", "The shift happened when..."] },
      { q: "Describe a time you felt truly proud of yourself — not for others, just for you.", zh: "描述一次你发自内心为自己骄傲的时刻。", hints: ["Nobody was watching, but...", "It mattered to me because...", "Quietly, I felt..."] },
      { q: "What emotion do you find hardest to express, and why do you think that is?", zh: "哪种情绪你最难表达？你觉得为什么？", hints: ["I tend to bottle up...", "It probably goes back to...", "When it does come out, it..."] },
      { q: "What advice would you give your younger self? Tell the story behind it.", zh: "你会给年轻的自己什么建议？讲讲背后的故事。", hints: ["If I could go back, I'd tell myself...", "At the time, I was so caught up in...", "It took me years to realize..."] },
      { q: "What role does luck play in where you are today?", zh: "运气在你走到今天这一步中扮演了什么角色？", hints: ["I'd be lying if I said...", "Being in the right place at the right time...", "That said, luck only works if..."] },
      { q: "Talk about a goodbye that was hard for you.", zh: "聊聊一次对你来说很难的告别。", hints: ["I kept putting it off because...", "The hardest part wasn't..., it was...", "Looking back, I'm glad we..."] },
      { q: "What do you think people misunderstand about you?", zh: "你觉得别人常误解你什么？", hints: ["People often assume I'm..., when actually...", "It comes across as..., but...", "Once people get to know me, ..."] },
      { q: "Describe something beautiful you saw recently and how it made you feel.", zh: "描述你最近见到的美好事物和它带给你的感受。", hints: ["I just stood there, taking it in.", "Something about it felt...", "It's hard to put into words, but..."] },
      { q: "If your life had chapters, what would this current chapter be called, and why?", zh: "如果人生有章节，你现在这一章叫什么？为什么？", hints: ["I'd call it..., because...", "The last chapter was about...", "I have a feeling the next one will be..."] },
      { q: "What's a fear you've mostly overcome? How did it happen?", zh: "你基本克服了什么恐惧？是怎么做到的？", hints: ["It used to paralyze me.", "Little by little, I...", "The breakthrough came when..."] },
      { q: "Do you think people can truly change? Argue your view with an example.", zh: "你认为人真的能改变吗？用例子论证你的观点。", hints: ["I'm inclined to think...", "Take ... for example.", "The counterargument would be..., but..."] },
      { q: "What's something unpopular you believe? Make your case.", zh: "你有什么不合主流的观点？为它辩护。", hints: ["This might be controversial, but...", "Hear me out: ...", "The evidence I'd point to is..."] },
      { q: "Talk about a person who shaped who you are. What did they give you?", zh: "聊聊塑造了你的一个人，TA 给了你什么？", hints: ["Without them, I doubt I would have...", "What they modeled for me was...", "I still hear their voice when..."] },
      { q: "When do you feel most like yourself?", zh: "什么时候你觉得最像真正的自己？", hints: ["It's usually when I'm...", "All the noise falls away and...", "In those moments, I don't have to..."] },
      { q: "What would you do differently if nobody judged you?", zh: "如果没人评判你，你会有什么不同的活法？", hints: ["I'd probably stop...", "Deep down, I've always wanted to...", "What holds me back is..."] },
      { q: "How do you want to be remembered by the people close to you?", zh: "你希望亲近的人如何记住你？", hints: ["Not for..., but for...", "I hope they'd say I was someone who...", "At the end of the day, ..."] },
      { q: "How has your idea of friendship changed as you've gotten older?", zh: "随着年龄增长，你对友谊的理解发生了什么变化？", hints: ["In my teens, friendship meant...", "These days, I care less about ... and more about...", "The friends who lasted are the ones who..."] },
      { q: "Tell me about a compliment you never forgot.", zh: "讲一句你至今难忘的夸奖。", hints: ["Years ago, someone told me...", "It stuck because at the time I...", "I've tried to live up to it by..."] },
      { q: "If you could say anything to your parents with zero consequences, what would it be?", zh: "如果可以毫无顾虑地对父母说任何话，你会说什么？", hints: ["I've never told them that...", "Part of me holds back because...", "Maybe what I really want them to know is..."] },
      { q: "What role does money actually play in happiness, in your experience?", zh: "以你的经验，钱在幸福中究竟扮演什么角色？", hints: ["Up to a point, money buys...", "The happiest I've ever been had nothing / everything to do with...", "What money can't fix is..."] },
      { q: "Talk about a time you forgave someone — or found that you couldn't.", zh: "讲一次你原谅某人——或发现自己无法原谅——的经历。", hints: ["For a long time, I held onto...", "What finally shifted was...", "Forgiveness, to me, isn't about..."] },
      { q: "What are you avoiding right now, and what's that avoidance costing you?", zh: "你现在在回避什么？这种回避的代价是什么？", hints: ["If I'm honest with myself, I keep putting off...", "The story I tell myself is...", "Deep down I know that until I face it, ..."] },
      { q: "You get one year, fully funded, no obligations. Walk me through it.", zh: "给你完全自由、衣食无忧的一年，你会怎么度过？", hints: ["The first month, I'd just...", "Then I'd finally pursue...", "By the end of the year, I'd want to have..."] },
      { q: "What part of your culture do you cherish most, and what part do you question?", zh: "你最珍视自己文化的哪部分？又质疑哪部分？", hints: ["Something I'll always carry with me is...", "At the same time, I struggle with...", "I want to keep ... but leave behind..."] },
      { q: "Name a book or film that genuinely changed how you think.", zh: "说一本真正改变了你思维方式的书或电影。", hints: ["Before it, I'd never questioned...", "There's one scene / passage where...", "It planted the idea that..."] },
      { q: "When did you last leave your comfort zone on purpose? What happened?", zh: "你上一次主动走出舒适区是什么时候？发生了什么？", hints: ["Every instinct told me not to, but...", "The scariest part turned out to be...", "It didn't go perfectly, and that's exactly why..."] },
      { q: "What do we owe to strangers, if anything?", zh: "我们对陌生人负有什么责任吗？", hints: ["At minimum, I think we owe each other...", "The tricky part is where to draw the line: ...", "A moment that shaped my view was..."] },
      { q: "Is ambition overrated? Defend your answer.", zh: "野心被高估了吗？为你的答案辩护。", hints: ["The version of ambition I reject is...", "But without some ambition, ...", "The healthiest ambitious people I know..."] },
      { q: "What does 'growing up' actually mean? When did it happen for you?", zh: "'长大'到底意味着什么？你是什么时候长大的？", hints: ["It's not about age — it's the moment you...", "For me it happened when...", "In some ways, I'm still..."] },
      { q: "Describe a place that holds a piece of you.", zh: "描述一个存放着你一部分灵魂的地方。", hints: ["Whenever I go back, ...", "So much happened there: ...", "Even if it changed completely, ..."] },
      { q: "What's the hardest truth you've had to accept about yourself?", zh: "关于你自己，你不得不接受的最难的真相是什么？", hints: ["For years I denied that...", "Accepting it was painful because...", "Strangely, it also freed me to..."] },
      { q: "What do you hope will be different for the next generation?", zh: "你希望下一代人的世界有什么不同？", hints: ["I hope they never have to...", "The thing my generation normalized that shouldn't be is...", "If we get one thing right, let it be..."] },
      { q: "When is quitting the right choice? Have you ever quit at the right time?", zh: "什么时候放弃才是正确的选择？你有过恰到好处的放弃吗？", hints: ["We glorify persistence, but...", "The signal for me is when...", "The best thing I ever quit was..."] },
      { q: "What has loneliness taught you?", zh: "孤独教会了你什么？", hints: ["My loneliest stretch was...", "At first I filled it with..., then...", "Now I can tell the difference between alone and..."] },
      { q: "If today repeated forever, Groundhog-Day style, what would you change first?", zh: "如果今天永远重复（土拨鼠之日式），你会先改变什么？", hints: ["Day one, I'd probably panic and...", "Eventually I'd use the time to...", "It makes me realize my ordinary day lacks..."] },
      { q: "How has your understanding of love changed — romantic, family, or friendship?", zh: "你对爱的理解发生了什么变化——爱情、亲情或友情？", hints: ["I used to think love was mostly...", "Watching ... taught me that...", "Now I'd define it as..."] },
      { q: "Describe your relationship with failure. Has it evolved?", zh: "描述你和失败的关系，它变了吗？", hints: ["Failure used to feel like proof that...", "The turning point was...", "Now when I fail, my first question is..."] },
      { q: "What would your 80-year-old self say about the things you worry about now?", zh: "80 岁的你会如何评价你现在的这些烦恼？", hints: ["She'd/He'd probably laugh at...", "But I think she'd/he'd take ... seriously.", "The advice would be something like..."] },
      { q: "What does 'enough' look like for you — money, achievements, possessions?", zh: "对你来说，'足够'是什么样子——金钱、成就、物质？", hints: ["The finish line keeps moving because...", "If I'm honest, enough would be...", "The trap I try to avoid is..."] },
      { q: "Describe a stranger's act you once witnessed that changed your view of people.", zh: "描述你目睹过的一个陌生人的举动，它改变了你对人的看法。", hints: ["I wasn't part of it — I just happened to see...", "Nobody clapped, nobody filmed it, they just...", "It made me wonder how often..."] },
      { q: "Which of your habits would genuinely surprise your closest friends?", zh: "你的哪个习惯会真正让你最亲近的朋友吃惊？", hints: ["Even my best friend doesn't know I...", "It started years ago when...", "I keep it to myself because..."] },
      { q: "What conversation do you wish people could have more openly?", zh: "你希望人们能更公开地谈论什么话题？", hints: ["We all pretend ... isn't happening.", "The silence around it costs us...", "If we could just say ... out loud, ..."] },
      { q: "How do you deal with envy — both feeling it and being envied?", zh: "你如何面对嫉妒——嫉妒别人，或被别人嫉妒？", hints: ["Scrolling through ..., I sometimes catch myself...", "I've learned envy is information: it points at...", "Being on the other side of it feels..."] },
      { q: "What's a promise you made to yourself? Are you keeping it?", zh: "你对自己许下过什么承诺？你在遵守吗？", hints: ["After ..., I swore I'd never...", "Keeping it is hardest when...", "So far, my track record is..."] },
      { q: "Whose expectations shaped you the most — and did that help or hurt?", zh: "谁的期望最深地塑造了你——那是帮助还是伤害？", hints: ["Growing up, ... expected me to...", "I only realized how deep it went when...", "Untangling their voice from mine has been..."] },
      { q: "What would you keep defending even if everyone around you disagreed?", zh: "即使身边所有人都反对，你仍会捍卫什么？", hints: ["Call me stubborn, but...", "I've tested this belief against...", "The day I stop defending it is the day..."] },
      { q: "How did your hometown shape your personality — for better or worse?", zh: "你的家乡如何塑造了你的性格——无论好坏？", hints: ["Growing up in a place where..., you learn to...", "The part of it I carry proudly is...", "The part I had to unlearn was..."] },
      { q: "What's your earliest vivid memory, and why do you think it stuck?", zh: "你最早的清晰记忆是什么？为什么它留了下来？", hints: ["I couldn't have been older than...", "The detail that stayed sharp is...", "Maybe it stuck because it was the first time I felt..."] },
      { q: "You're writing a letter to be opened in ten years. What goes in it?", zh: "你在写一封十年后打开的信，里面写什么？", hints: ["First, I'd ask my future self whether...", "I'd want to remind them how ... felt.", "The last line would be..."] },
      { q: "What do you understand about your parents now that you didn't before?", zh: "关于父母，你现在理解了哪些过去不理解的东西？", hints: ["As a kid, I judged them for...", "Then I hit the same age and realized...", "What I owe them an apology for is..."] },
      { q: "When does time move fastest for you, and when does it crawl?", zh: "什么时候你觉得时间飞逝？什么时候度日如年？", hints: ["Hours vanish when I'm...", "Time crawls whenever...", "It makes me think the clock measures ... not..."] },
      { q: "What small kindness from years ago do you still remember?", zh: "多年前的哪个小小善意你至今记得？", hints: ["They probably forgot it five minutes later, but...", "It came exactly when I...", "I've tried to pass it on by..."] },
      { q: "If your mind has a default worry it returns to, what is it?", zh: "如果你的大脑有个'默认焦虑'，它是什么？", hints: ["Whenever things go quiet, my mind drifts to...", "Rationally I know..., but...", "The only thing that quiets it is..."] },
      { q: "Which value will you pass on to the next generation, and which will you end?", zh: "你会传承哪种价值观给下一代？又会终结哪种？", hints: ["From my family, I'll keep...", "But the cycle of ... ends with me.", "It's hard because ending it means..."] },
      { q: "How do you want to age? Describe yourself at sixty.", zh: "你想如何老去？描述 60 岁的自己。", hints: ["I refuse to become someone who...", "At sixty, I hope my days look like...", "The kind of old person I admire is..."] },
      { q: "What part of your personality is armor, and what's underneath it?", zh: "你性格中哪部分是盔甲？盔甲下面是什么？", hints: ["People read me as..., but that started as protection.", "I put it on around the time...", "The few who've seen underneath know I'm actually..."] },
      { q: "What question are you afraid to know the answer to?", zh: "你害怕知道答案的问题是什么？", hints: ["I've never dared to ask...", "Part of me prefers the uncertainty because...", "If the answer were yes / no, I'd have to..."] },
      { q: "What has this year taught you that last year couldn't have?", zh: "今年教会了你什么去年学不会的东西？", hints: ["Last year I wasn't ready to hear...", "It took ... happening for me to see...", "If the lesson has a single sentence, it's..."] },
    ],
  },
  situations: {
    label: "情景演练",
    items: [
      { q: "Role-play: Your new laptop arrived with a cracked screen. Call customer service and get a replacement.", zh: "情景：新买的笔记本电脑屏幕碎了，打电话给客服要求换货。", hints: ["I'm calling about an order I received yesterday...", "The screen was cracked right out of the box.", "I'd like a replacement rather than a refund."] },
      { q: "Role-play: Order dinner for a table of four — one vegetarian, one seafood allergy.", zh: "情景：为四人点餐——一位素食，一位海鲜过敏。", hints: ["Could we get ... to share, please?", "Just to check, does this contain any...?", "One of us has a serious allergy, so..."] },
      { q: "Role-play: You arrive at the hotel at midnight and they can't find your booking.", zh: "情景：午夜到达酒店，前台找不到你的预订。", hints: ["I have a confirmation email right here...", "I understand it's not your fault, but I need a room tonight.", "What options do we have right now?"] },
      { q: "Role-play: Your flight just got cancelled. Talk to the counter agent about rebooking.", zh: "情景：航班被取消，与柜台工作人员沟通改签。", hints: ["What are my options for getting there today?", "Is there a connection through another city?", "Will the airline cover the hotel if I'm stuck overnight?"] },
      { q: "Role-play: Describe your symptoms to a doctor — you've had a headache and fever for two days.", zh: "情景：向医生描述症状——头痛发烧两天了。", hints: ["It started two days ago with...", "The pain is more of a dull ache / sharp pain.", "It gets worse when I..."] },
      { q: "Role-play: Explain to the barber exactly what haircut you want.", zh: "情景：向理发师准确描述你想要的发型。", hints: ["Just a trim, about an inch off, please.", "Keep the length on top, shorter on the sides.", "Last time it was too ..., so this time..."] },
      { q: "Role-play: Make small talk with your taxi driver who asks where you're from.", zh: "情景：和问你从哪里来的出租车司机闲聊。", hints: ["I'm originally from..., have you been?", "How long have you been driving here?", "What should I absolutely see while I'm in town?"] },
      { q: "Role-play: Ask a stranger to take your photo, then ask for directions to the metro.", zh: "情景：请陌生人帮你拍照，然后问去地铁站的路。", hints: ["Excuse me, would you mind taking a photo of us?", "Could you get the building in the background?", "Also, how do I get to the nearest metro station?"] },
      { q: "Role-play: You're waiting with the interviewer in the elevator before your job interview. Break the ice.", zh: "情景：面试前和面试官同乘电梯，打破沉默。", hints: ["Thanks for making time today — I've been looking forward to this.", "The office is impressive — how long has the team been here?", "I read about your recent launch — congratulations."] },
      { q: "Role-play: Negotiate the rent down with your landlord for renewing the lease.", zh: "情景：续约时和房东谈降房租。", hints: ["I've been a reliable tenant for ... — always paid on time.", "Similar units nearby are going for...", "If we can settle on ..., I'll sign for two years today."] },
      { q: "Role-play: Your neighbor plays loud music at 1 a.m. Knock on their door and sort it out politely.", zh: "情景：邻居凌晨一点还在大声放音乐，礼貌上门解决。", hints: ["Sorry to bother you this late...", "I can hear the bass pretty clearly through the wall.", "Could we agree on keeping it down after eleven?"] },
      { q: "Role-play: Order a complicated custom coffee, then it comes out wrong. Handle it.", zh: "情景：点一杯复杂定制咖啡，结果做错了，处理这个情况。", hints: ["Could I get a ... with oat milk, half the syrup, extra shot?", "Sorry, I think this might be someone else's — I ordered...", "No rush at all, whenever you get a chance."] },
      { q: "Role-play: Ask gym staff about membership prices, then about how to cancel before signing up.", zh: "情景：咨询健身房会员价格，签约前先问清如何取消。", hints: ["What do your membership plans look like?", "Are there any joining fees or hidden costs?", "Hypothetically, how easy is it to cancel?"] },
      { q: "Role-play: The ATM swallowed your card. Explain the situation inside the bank.", zh: "情景：ATM 吞了你的卡，进银行说明情况。", hints: ["Your machine outside just kept my card.", "I was mid-transaction when the screen...", "How long will a replacement take, and what do I do meanwhile?"] },
      { q: "Role-play: At the pharmacy, describe your cold symptoms and ask about dosage.", zh: "情景：在药店描述感冒症状并询问用药剂量。", hints: ["I've got a blocked nose and a sore throat.", "Is this safe to take with...?", "How many times a day, and with or without food?"] },
      { q: "Role-play: Your suitcase never showed up on the belt. File a report at the airport desk.", zh: "情景：行李没有出现在传送带上，到机场柜台登记。", hints: ["My bag didn't come out — flight ... from ...", "It's a medium grey suitcase with a red ribbon on the handle.", "How will I be updated, and what's covered in the meantime?"] },
      { q: "Role-play: Invite a foreign colleague to a hotpot dinner and explain how it works.", zh: "情景：邀请外国同事吃火锅并解释怎么吃。", hints: ["We're doing hotpot Friday — you in?", "Basically, there's a boiling broth in the middle and...", "Pro tip: don't leave the ... in too long."] },
      { q: "Role-play: You're meeting your friend's parents for the first time at dinner.", zh: "情景：第一次和朋友的父母吃饭见面。", hints: ["It's so nice to finally meet you — I've heard so much.", "The food is wonderful — did you make this yourself?", "So how has ... described me? Should I be worried?"] },
      { q: "Role-play: You missed your best friend's important event. Apologize sincerely.", zh: "情景：你错过了挚友的重要活动，真诚道歉。", hints: ["I know sorry doesn't cut it...", "There's no excuse — I should have...", "Let me make it up to you: ..."] },
      { q: "Role-play: Explain Spring Festival (or your favorite festival) to a curious foreigner.", zh: "情景：向好奇的外国人解释春节（或你最喜欢的节日）。", hints: ["Think of it as ... meets ...", "The whole country basically...", "The part you'd love most is..."] },
      { q: "Role-play: Call the dentist to reschedule your appointment for next week.", zh: "情景：打电话给牙医诊所，把预约改到下周。", hints: ["I have an appointment this Thursday at 3, but something's come up.", "Do you have anything early next week?", "Morning works best for me, if possible."] },
      { q: "Role-play: Return a sweater without the receipt and negotiate store credit.", zh: "情景：没有小票退一件毛衣，协商换成商店积分。", hints: ["I got this as a gift, so I don't have the receipt.", "It still has the tags on, unworn.", "Would store credit or an exchange be possible?"] },
      { q: "Role-play: Friends are visiting your new place for the first time. Give them the tour.", zh: "情景：朋友第一次来你的新家，带他们参观。", hints: ["Welcome! Let me give you the grand tour.", "This is my favorite corner because...", "Ignore the mess in... — we don't talk about that room."] },
      { q: "Role-play: Call your Airbnb host — the heating isn't working and it's freezing.", zh: "情景：打给民宿房东——暖气坏了，屋里很冷。", hints: ["Sorry to call this late, but the heating seems to be broken.", "I've tried ..., but nothing changed.", "Could someone take a look tonight, or should we talk about..."] },
      { q: "Role-play: Ask your professor or boss for a deadline extension — you have a good reason.", zh: "情景：向教授或上司申请延期——你有正当理由。", hints: ["I want to flag this early rather than at the last minute.", "The reason is..., which I couldn't have planned around.", "With two more days, I can deliver ... properly."] },
      { q: "Role-play: Your internet is down. Get through tech support's script and to a solution.", zh: "情景：家里断网，应付技术支持的流程话术并解决问题。", hints: ["Yes, I've already restarted the router twice.", "The light is blinking red, not green.", "Can we skip ahead — I think it needs a technician visit."] },
      { q: "Role-play: You're at a party where you know absolutely nobody. Start three conversations.", zh: "情景：在一个谁都不认识的聚会上，发起三段对话。", hints: ["So, how do you know the host?", "I have to ask — where did you get...?", "I'm new here too — want to judge the snack table together?"] },
      { q: "Role-play: Give a one-minute farewell speech for a colleague who's leaving.", zh: "情景：为离职同事做一分钟欢送致辞。", hints: ["When ... joined, none of us expected...", "What we'll miss most is...", "Wherever you land, they're lucky to have you."] },
      { q: "Role-play: Give a short toast at your best friend's wedding.", zh: "情景：在挚友婚礼上做简短祝酒。", hints: ["For those who don't know me, I'm the one who...", "I've never seen ... as happy as when...", "So raise your glasses to..."] },
      { q: "Role-play: Your friend just failed an important exam. Comfort them without empty words.", zh: "情景：朋友重要考试失利，安慰 TA 但别说空话。", hints: ["This sucks, and I'm not going to pretend it doesn't.", "One exam doesn't get to define...", "When you're ready, let's figure out round two together."] },
      { q: "Role-play: Convince your friend to watch your favorite show tonight instead of scrolling their phone.", zh: "情景：说服朋友今晚看你最爱的剧，而不是刷手机。", hints: ["Give me one episode — that's all I ask.", "It's exactly your kind of story: ...", "If you don't like it by episode two, I'll never mention it again."] },
      { q: "Role-play: Sell your old phone to a cautious buyer. Answer their questions honestly.", zh: "情景：把旧手机卖给一位谨慎的买家，诚实回答问题。", hints: ["Battery health is at ..., I'll show you in settings.", "One small scratch here, but the screen itself...", "I can knock off ... if you take it today."] },
      { q: "Role-play: You're the tour guide. Introduce your favorite spot in the city to visitors.", zh: "情景：你是导游，向游客介绍城里你最爱的地方。", hints: ["If you only see one place today, make it this.", "Fun fact most tourists never hear: ...", "Watch your step here — and look up in three, two, one..."] },
      { q: "Role-play: A cyclist scratched your car (or bike). Exchange information and describe the incident for insurance.", zh: "情景：一位骑车人剐蹭了你的车，交换信息并向保险描述事故。", hints: ["Is everyone okay? That's the main thing.", "Let's exchange contacts and take photos of...", "For the record, I was ... when it happened."] },
      { q: "Role-play: Coffee chat — ask a senior person you admire for career advice without being awkward.", zh: "情景：咖啡闲聊——向敬佩的前辈请教职业建议且不尴尬。", hints: ["Thanks for making the time — I'll keep it to twenty minutes.", "When you were at my stage, how did you decide...?", "What do you wish someone had told you back then?"] },
      { q: "Role-play: A pushy salesperson won't let you leave. Decline firmly but politely.", zh: "情景：推销员纠缠不放，坚定而礼貌地拒绝。", hints: ["I appreciate the walkthrough, but I'm not buying today.", "I don't need the upgrade — I'm happy with what I have.", "I really do have to go now. Have a good one."] },
      { q: "Role-play: The delivery app is down. Call the restaurant, order by phone, and explain your tricky address.", zh: "情景：外卖软件崩了，打电话向餐厅点餐并说明复杂地址。", hints: ["Hi, I'd like to place an order for delivery, please.", "The building is behind the ..., second gate on the left.", "If the rider gets lost, tell them to call me at..."] },
      { q: "Role-play: It's 2 a.m., you're locked out of your hotel room and your key card is inside.", zh: "情景：凌晨两点被锁在酒店房间外，房卡在屋里。", hints: ["I feel ridiculous, but I've locked myself out.", "Room 1204, under the name...", "I can show you my ID — it's... also in the room. What now?"] },
      { q: "Role-play: It's your first day. Introduce yourself to the whole team in sixty seconds.", zh: "情景：入职第一天，用 60 秒向全组自我介绍。", hints: ["I'm the new ... — please forgive the name-forgetting phase.", "Most recently I was at ..., working on...", "Coffee's on me this week if you show me where the good machine is."] },
      { q: "Role-play: Airport security asks about the items in your bag. Explain calmly.", zh: "情景：机场安检询问你包里的物品，冷静解释。", hints: ["That's a power bank — here, I can take it out.", "The liquid is medication; I have the prescription.", "Sure, go ahead and open it — nothing fragile inside."] },
    ],
  },
};

// ============ 语块库 ============
const PHRASES = [
  {
    cat: "情感细腻表达",
    items: [
      { en: "I have mixed feelings about it.", zh: "我对此心情复杂。", ex: "I have mixed feelings about moving abroad — excited, but a little scared." },
      { en: "It's bittersweet.", zh: "苦乐参半 / 百感交集。", ex: "Graduation was bittersweet — proud of us, sad to say goodbye." },
      { en: "I'm a bit torn.", zh: "我有点纠结（两难）。", ex: "I'm a bit torn between the two offers." },
      { en: "It didn't sit right with me.", zh: "这事让我心里不舒服/膈应。", ex: "The way he said it didn't sit right with me." },
      { en: "I was blown away.", zh: "我被彻底震撼/惊艳到了。", ex: "I was blown away by her presentation." },
      { en: "It caught me off guard.", zh: "让我措手不及。", ex: "The question caught me off guard, so I froze for a second." },
      { en: "I can't quite put it into words.", zh: "我说不太上来（难以言表）。", ex: "I can't quite put it into words, but the song moves me every time." },
      { en: "Deep down, I knew...", zh: "内心深处，我知道……", ex: "Deep down, I knew it was time to leave." },
      { en: "annoyed → frustrated → furious", zh: "恼火 → 挫败恼怒 → 暴怒（愤怒三级）", ex: "I was annoyed at first, then frustrated, and by midnight — furious." },
      { en: "pleased → delighted → thrilled → over the moon", zh: "满意 → 高兴 → 兴奋 → 欣喜若狂（开心四级）", ex: "She wasn't just pleased with the gift — she was over the moon." },
      { en: "It hit me hard.", zh: "对我打击很大 / 让我深受触动。", ex: "The news hit me harder than I expected." },
      { en: "I'm overwhelmed — in a good way.", zh: "我情绪满溢——是好的那种。", ex: "All these birthday messages... I'm overwhelmed, in a good way." },
      { en: "nervous → anxious → terrified", zh: "紧张 → 焦虑 → 吓坏了（恐惧三级）", ex: "I was nervous before the interview, anxious in the waiting room, and terrified when they called my name." },
      { en: "sad → heartbroken → devastated", zh: "难过 → 心碎 → 崩溃（悲伤三级）", ex: "She was sad about the move, heartbroken to leave her friends, devastated when the goodbye came." },
      { en: "tired → drained → burned out", zh: "累 → 被掏空 → 燃尽（疲惫三级）", ex: "I'm not just tired — I'm completely drained, borderline burned out." },
      { en: "surprised → stunned → speechless", zh: "惊讶 → 震惊 → 说不出话（惊讶三级）", ex: "I was surprised by the offer, stunned by the number, and honestly speechless by the end." },
      { en: "It's been weighing on me.", zh: "这件事一直压在我心头。", ex: "That unfinished conversation has been weighing on me all week." },
      { en: "I got cold feet.", zh: "我临阵退缩了。", ex: "I was going to sign up for the marathon, but I got cold feet." },
      { en: "A wave of relief washed over me.", zh: "一阵如释重负的感觉涌上心头。", ex: "When the results came back clear, a wave of relief washed over me." },
      { en: "I have a soft spot for...", zh: "我对……格外心软/偏爱。", ex: "I have a soft spot for old bookstores — I can never walk past one." },
      { en: "It means the world to me.", zh: "这对我无比重要。", ex: "You flew in just for my graduation? That means the world to me." },
      { en: "I was on edge all day.", zh: "我一整天都提心吊胆。", ex: "Waiting for the results, I was on edge all day." },
      { en: "It's a weight off my shoulders.", zh: "如释重负。", ex: "Finally submitting the thesis was a huge weight off my shoulders." },
      { en: "guilty pleasure", zh: "带着负罪感的小快乐", ex: "Trashy reality shows are my guilty pleasure." },
      { en: "I'm proud of how far I've come.", zh: "我为自己一路走来的成长感到骄傲。", ex: "Looking at my old writing, I'm proud of how far I've come." },
      { en: "I feel seen.", zh: "我感觉被理解/被看见了。", ex: "When she described exactly what I'd been going through, I felt seen." },
    ],
  },
  {
    cat: "观点与委婉",
    items: [
      { en: "I see where you're coming from, but...", zh: "我理解你的出发点，但是……", ex: "I see where you're coming from, but the data says otherwise." },
      { en: "To be fair, ...", zh: "平心而论……", ex: "To be fair, nobody saw the market crash coming." },
      { en: "That's a fair point.", zh: "这话有道理。", ex: "That's a fair point — I hadn't considered the cost." },
      { en: "I'd push back a little on that.", zh: "这点我想提出些不同意见。", ex: "I'd push back a little on that timeline — it feels too tight." },
      { en: "It depends on how you look at it.", zh: "取决于你从哪个角度看。", ex: "Was it a failure? It depends on how you look at it." },
      { en: "I'm not saying...; I'm just saying...", zh: "我不是说……我只是说……", ex: "I'm not saying it's bad; I'm just saying we can do better." },
      { en: "From where I stand, ...", zh: "在我看来（从我的立场）……", ex: "From where I stand, the risk outweighs the reward." },
      { en: "Playing devil's advocate for a second, ...", zh: "我唱个反调（换个角度挑战一下）……", ex: "Playing devil's advocate for a second — what if users hate it?" },
      { en: "That said, ...", zh: "话虽如此……", ex: "It's expensive. That said, it might save us months." },
      { en: "I might be wrong, but...", zh: "我可能不对，但……", ex: "I might be wrong, but I think the meeting moved to Friday." },
      { en: "That's one way to look at it.", zh: "这是一种看法。（不完全同意）", ex: "That's one way to look at it — though I'd frame it differently." },
      { en: "I wouldn't go that far.", zh: "我倒不至于那么认为。", ex: "He's disorganized, sure, but 'incompetent'? I wouldn't go that far." },
      { en: "It's a bit of a stretch.", zh: "这有点牵强。", ex: "Calling it a revolution is a bit of a stretch — it's an improvement." },
      { en: "There's something to be said for...", zh: "……还是有可取之处的。", ex: "There's something to be said for doing things the slow way." },
      { en: "For what it's worth, ...", zh: "不管有没有用，说一句……", ex: "For what it's worth, I thought your proposal was the strongest." },
      { en: "Correct me if I'm wrong, but...", zh: "如果我说错了请纠正，但……", ex: "Correct me if I'm wrong, but didn't we agree on Friday as the deadline?" },
    ],
  },
  {
    cat: "职场高频",
    items: [
      { en: "Let me get back to you on that.", zh: "这个我稍后答复你。", ex: "Good question — let me get back to you on that after lunch." },
      { en: "I'll keep you posted.", zh: "有进展我随时同步你。", ex: "The fix is in review. I'll keep you posted." },
      { en: "Can we take this offline?", zh: "这个我们会后单聊？", ex: "This is getting detailed — can we take it offline?" },
      { en: "Let's circle back to this next week.", zh: "我们下周再回到这个话题。", ex: "No decision today; let's circle back next week." },
      { en: "I don't have the bandwidth right now.", zh: "我现在实在没有精力/时间。", ex: "I'd love to help, but I don't have the bandwidth this sprint." },
      { en: "Let's get everyone on the same page.", zh: "让大家信息同步/达成共识。", ex: "Before we start, let's get everyone on the same page." },
      { en: "Just to play it safe, ...", zh: "保险起见……", ex: "Just to play it safe, let's back up the database first." },
      { en: "Walk me through it.", zh: "给我从头讲一遍。", ex: "Before I approve, walk me through the numbers." },
      { en: "A ballpark figure is fine.", zh: "给个大概数字就行。", ex: "No need to be exact — a ballpark figure is fine." },
      { en: "Let's not reinvent the wheel.", zh: "咱们别重复造轮子。", ex: "There's a library for this — let's not reinvent the wheel." },
      { en: "Let's touch base tomorrow.", zh: "我们明天碰一下（简短沟通）。", ex: "No need for a long meeting — let's just touch base tomorrow morning." },
      { en: "I'll loop you in.", zh: "我会把你拉进讨论/抄送你。", ex: "We're deciding the rollout plan — I'll loop you in on the email thread." },
      { en: "Moving forward, ...", zh: "从今往后 / 接下来……", ex: "Moving forward, all changes need a review before merging." },
      { en: "That's out of scope for now.", zh: "这超出当前范围了。", ex: "Great idea, but it's out of scope for this release — let's note it down." },
      { en: "Let's table this for now.", zh: "这个议题先搁置。", ex: "We're running out of time — let's table this and cover it next week." },
      { en: "low-hanging fruit", zh: "容易实现的目标/唾手可得的成果", ex: "Before the big redesign, let's grab the low-hanging fruit first." },
      { en: "I'll take the lead on this.", zh: "这件事我来牵头。", ex: "Since I know the client, I'll take the lead on this one." },
      { en: "Do we have sign-off from...?", zh: "……那边批准/拍板了吗？", ex: "Before we ship, do we have sign-off from legal?" },
    ],
  },
  {
    cat: "日常高频",
    items: [
      { en: "It's up to you.", zh: "你来定。", ex: "Pizza or hotpot? It's up to you." },
      { en: "I'm down.", zh: "我加入 / 我愿意。", ex: "Karaoke tonight? I'm down!" },
      { en: "That works for me.", zh: "我这边没问题。", ex: "Saturday at 3? That works for me." },
      { en: "Long story short, ...", zh: "长话短说……", ex: "Long story short, we missed the train and slept in the station." },
      { en: "It's not my cup of tea.", zh: "不是我的菜。", ex: "Horror movies are just not my cup of tea." },
      { en: "Let's play it by ear.", zh: "到时候见机行事。", ex: "Not sure about the weather — let's play it by ear." },
      { en: "No worries — these things happen.", zh: "没事儿，这种事难免。", ex: "You're late? No worries — these things happen." },
      { en: "I could really go for some coffee.", zh: "我现在特别想来杯咖啡。", ex: "After that meeting, I could really go for some coffee." },
      { en: "It slipped my mind.", zh: "我一下子给忘了。", ex: "Sorry, your birthday totally slipped my mind." },
      { en: "I'm running late.", zh: "我要迟到了。", ex: "Traffic is crazy — I'm running late, start without me." },
      { en: "It's such a hassle.", zh: "太麻烦了。", ex: "Returning stuff online is such a hassle — all those forms." },
      { en: "I'm swamped.", zh: "我忙得不可开交。", ex: "Can we do next week instead? I'm swamped right now." },
      { en: "Let's grab a bite.", zh: "我们去随便吃点东西吧。", ex: "I'm starving — let's grab a bite before the movie." },
      { en: "My treat.", zh: "我请客。", ex: "Put your wallet away — my treat this time." },
      { en: "I'm beat.", zh: "我累瘫了。", ex: "Three meetings back to back... I'm beat." },
      { en: "It hit the spot.", zh: "太解馋/太到位了。", ex: "A hot bowl of noodles on a rainy day — it really hit the spot." },
      { en: "Speak of the devil.", zh: "说曹操，曹操到。", ex: "Speak of the devil — we were just talking about you!" },
      { en: "Better late than never.", zh: "迟到总比不到好。", ex: "He finally apologized. Better late than never, I guess." },
    ],
  },
  {
    cat: "讲故事与叙述",
    items: [
      { en: "So there I was, ...", zh: "当时我正……（故事开场）", ex: "So there I was, standing in the rain with no umbrella." },
      { en: "Out of nowhere, ...", zh: "突然间/毫无征兆地……", ex: "Out of nowhere, the power went out." },
      { en: "To make matters worse, ...", zh: "更糟的是……", ex: "To make matters worse, my phone died too." },
      { en: "Looking back, ...", zh: "回过头看……", ex: "Looking back, it was the best thing that ever happened to me." },
      { en: "At that point, I had no idea that...", zh: "那时我完全不知道……", ex: "At that point, I had no idea that call would change everything." },
      { en: "It turned out that...", zh: "结果发现……", ex: "It turned out that we'd been waiting at the wrong gate." },
      { en: "The funny thing is, ...", zh: "有意思的是……", ex: "The funny thing is, we became best friends after that fight." },
      { en: "And that's how I ended up...", zh: "就这样，我最终……（收尾）", ex: "And that's how I ended up living in Shanghai." },
      { en: "Picture this: ...", zh: "想象一下这个画面：……", ex: "Picture this: midnight, pouring rain, and our car dies on the highway." },
      { en: "Fast forward to...", zh: "快进到……", ex: "We lost touch after school. Fast forward to last month — we're coworkers." },
      { en: "Just my luck, ...", zh: "我就是这么倒霉……", ex: "Just my luck, the one day I forget my umbrella, it pours." },
      { en: "Against all odds, ...", zh: "在几乎不可能的情况下……", ex: "Against all odds, the tiny startup landed the biggest client in the industry." },
      { en: "In the blink of an eye, ...", zh: "一眨眼的工夫……", ex: "In the blink of an eye, the kids were grown and the house was quiet." },
      { en: "Little did I know, ...", zh: "我当时完全不知道……", ex: "I said yes to a coffee. Little did I know, it would change my whole career." },
    ],
  },
  {
    cat: "万能接话与回应",
    items: [
      { en: "That makes total sense.", zh: "太有道理了/完全说得通。", ex: "Ah, you moved for the schools — that makes total sense." },
      { en: "No way! Then what?", zh: "不会吧！然后呢？", ex: "He quit on the spot? No way! Then what?" },
      { en: "I know, right?", zh: "就是说啊！（强烈同感）", ex: "'This weather is unreal.' — 'I know, right?'" },
      { en: "Tell me about it.", zh: "可不是嘛（我太懂了）。", ex: "'Rent keeps going up.' — 'Tell me about it. Mine jumped 20%.'" },
      { en: "You've got a point.", zh: "你说得有道理。", ex: "You've got a point — waiting might actually be riskier." },
      { en: "Wait, back up a second.", zh: "等等，倒回去一点（再讲一遍）。", ex: "Wait, back up a second — she said WHAT at the meeting?" },
      { en: "That's wild.", zh: "太离谱/太夸张了。", ex: "Twins, born in different years? That's wild." },
      { en: "Same here.", zh: "我也是。", ex: "'I can't function without coffee.' — 'Same here.'" },
      { en: "Good for you!", zh: "真为你高兴！", ex: "You finally asked for the promotion? Good for you!" },
      { en: "That sucks. I'm sorry.", zh: "太糟糕了，我很遗憾。", ex: "Your flight got cancelled again? That sucks. I'm sorry." },
      { en: "What a coincidence!", zh: "太巧了！", ex: "You were on the same train? What a coincidence!" },
      { en: "Now we're talking!", zh: "这才像话/这才对嘛！", ex: "Free food AND a bonus? Now we're talking!" },
    ],
  },
  {
    cat: "委婉拒绝与请求",
    items: [
      { en: "I'd love to, but I can't make it.", zh: "我很想去，但实在去不了。", ex: "I'd love to, but I can't make it Friday — rain check?" },
      { en: "Can I get back to you on that?", zh: "我能晚点答复你吗？", ex: "I need to check my schedule first — can I get back to you on that?" },
      { en: "Would you mind giving me a hand?", zh: "你介意搭把手吗？", ex: "Would you mind giving me a hand with these boxes?" },
      { en: "Is there any chance you could...?", zh: "有没有可能请你……？", ex: "Is there any chance you could cover my shift on Saturday?" },
      { en: "I'm going to pass this time.", zh: "这次我就不参加了。", ex: "Thanks for the invite, but I'm going to pass this time." },
      { en: "It's not really my thing, to be honest.", zh: "说实话这不太对我的胃口。", ex: "Karaoke is not really my thing, to be honest — but you guys have fun!" },
      { en: "Could you do me a huge favor?", zh: "能帮我个大忙吗？", ex: "Could you do me a huge favor and water my plants next week?" },
      { en: "I don't want to impose, but...", zh: "我不想添麻烦，但是……", ex: "I don't want to impose, but could I crash on your couch for a night?" },
      { en: "Let me sleep on it.", zh: "让我考虑一晚。", ex: "It's a big decision — let me sleep on it and call you tomorrow." },
      { en: "I appreciate the offer, but I'm all set.", zh: "谢谢好意，不过我不需要了。", ex: "I appreciate the offer, but I'm all set — everything's packed." },
      { en: "Any chance we could push it to next week?", zh: "有可能推到下周吗？", ex: "Something came up — any chance we could push our dinner to next week?" },
      { en: "I hate to ask, but could you cover for me?", zh: "真不好意思开口，你能替我顶一下吗？", ex: "I hate to ask, but could you cover for me at the morning standup?" },
    ],
  },
  {
    cat: "高频动词短语",
    items: [
      { en: "figure out", zh: "弄清楚，想明白", ex: "It took me a week to figure out why the code kept crashing." },
      { en: "come up with", zh: "想出（点子/方案）", ex: "She came up with a brilliant name for the product." },
      { en: "put off", zh: "推迟，拖延", ex: "I've been putting off that dentist appointment for months." },
      { en: "end up", zh: "最终（意外地）成为/处于", ex: "We planned a quiet dinner and ended up singing karaoke till 2 a.m." },
      { en: "run into", zh: "偶遇；碰上（问题）", ex: "I ran into my old professor at the airport." },
      { en: "catch up", zh: "叙旧；赶上进度", ex: "Let's grab coffee and catch up — it's been ages." },
      { en: "turn out", zh: "结果是，原来是", ex: "The 'stranger' turned out to be my neighbor's brother." },
      { en: "work out", zh: "顺利解决；健身", ex: "Don't worry about the visa — it'll all work out." },
      { en: "look forward to", zh: "期待", ex: "I'm really looking forward to the trip — I've been counting the days." },
      { en: "get around to", zh: "终于抽出时间做", ex: "I finally got around to organizing my photos from last year." },
      { en: "follow up on", zh: "跟进", ex: "I'll follow up on the invoice first thing tomorrow." },
      { en: "bring up", zh: "提起（话题）", ex: "I didn't want to bring up the layoffs at dinner." },
      { en: "point out", zh: "指出", ex: "She pointed out a flaw in the plan that we'd all missed." },
      { en: "sort out", zh: "解决，理清", ex: "Give me an hour to sort out the schedule conflict." },
      { en: "put up with", zh: "忍受，容忍", ex: "I don't know how you put up with that noise every night." },
      { en: "run out of", zh: "用完，耗尽", ex: "We ran out of coffee halfway through the all-nighter." },
      { en: "come across", zh: "偶然发现；给人以……印象", ex: "I came across an old photo of us while cleaning. / He comes across as confident." },
      { en: "take up", zh: "开始培养（爱好）；占用", ex: "I took up swimming last spring. / The piano takes up half the room." },
      { en: "cut down on", zh: "减少，削减", ex: "I'm trying to cut down on sugar — trying being the key word." },
      { en: "fall through", zh: "（计划）落空，泡汤", ex: "The apartment deal fell through at the last minute." },
      { en: "get over", zh: "从……中走出来，克服", ex: "It took me months to get over that breakup." },
      { en: "pull off", zh: "成功做成（难事）", ex: "Nobody thought we could organize it in a week, but we pulled it off." },
      { en: "look up to", zh: "敬仰，尊敬", ex: "I've always looked up to my grandmother — toughest person I know." },
      { en: "give up on", zh: "对……放弃希望", ex: "Never give up on a language — plateaus always pass." },
    ],
  },
  {
    cat: "话语组织与连接",
    items: [
      { en: "That reminds me...", zh: "这让我想起……（自然切换话题）", ex: "That reminds me — did you ever call the landlord back?" },
      { en: "Speaking of which, ...", zh: "说到这个……", ex: "Speaking of which, how did your interview go?" },
      { en: "Anyway, where was I?", zh: "话说回来，我刚才说到哪儿了？", ex: "Sorry for the tangent — anyway, where was I? Right, the trip." },
      { en: "On a related note, ...", zh: "说个相关的事……", ex: "On a related note, the client asked about pricing again." },
      { en: "To put it another way, ...", zh: "换句话说……", ex: "To put it another way, we're spending more to earn less." },
      { en: "Here's the thing: ...", zh: "关键是这样的……", ex: "Here's the thing: I never actually agreed to host it." },
      { en: "If anything, ...", zh: "要说有什么区别的话，反而……", ex: "The criticism didn't discourage me — if anything, it fired me up." },
      { en: "For starters, ...", zh: "首先/先说一点……", ex: "Why do I love this city? For starters, the food is unbeatable." },
      { en: "On top of that, ...", zh: "更何况/除此之外……", ex: "The room was tiny, and on top of that, the WiFi barely worked." },
      { en: "Then again, ...", zh: "不过话说回来……", ex: "I'd love a bigger place. Then again, I'd have to clean it." },
      { en: "All things considered, ...", zh: "综合来看……", ex: "All things considered, the trip was worth every penny." },
      { en: "The bottom line is...", zh: "归根结底/最重要的是……", ex: "The bottom line is we can't afford to delay again." },
      { en: "Where do I even start?", zh: "让我从何说起呢？", ex: "You want the whole story? Where do I even start?" },
      { en: "...and that's saying something.", zh: "……这可不是随便说说（很能说明问题）。", ex: "It's the best hotpot I've had — and I'm from Chongqing, so that's saying something." },
    ],
  },
  {
    cat: "夸赞与鼓励",
    items: [
      { en: "You nailed it!", zh: "你搞定了/太到位了！", ex: "That presentation? You absolutely nailed it." },
      { en: "Hats off to you.", zh: "向你致敬/佩服。", ex: "Running a marathon at 50 — hats off to you." },
      { en: "You're onto something.", zh: "你这个思路有戏。", ex: "Keep going — I think you're onto something with this idea." },
      { en: "That's a game-changer.", zh: "这能改变全局。", ex: "Wait, it syncs automatically? That's a game-changer." },
      { en: "You make it look easy.", zh: "你让这事看起来毫不费力。", ex: "Twenty dumplings in ten minutes — you make it look easy." },
      { en: "I'm impressed — seriously.", zh: "我真的被打动了。", ex: "You taught yourself to code in six months? I'm impressed — seriously." },
      { en: "Keep it up!", zh: "继续保持！", ex: "Your English is getting noticeably smoother — keep it up!" },
      { en: "You've outdone yourself.", zh: "你超越了自己。", ex: "This dinner is incredible — you've outdone yourself." },
      { en: "Give yourself some credit.", zh: "别太谦虚，你值得肯定。", ex: "You call that luck? Give yourself some credit — you earned it." },
      { en: "You handled that like a pro.", zh: "你处理得像个专业选手。", ex: "That angry customer? You handled it like a pro." },
      { en: "It shows.", zh: "看得出来（你的努力）。", ex: "You've been practicing every day, and honestly, it shows." },
      { en: "You were born for this.", zh: "你天生就是干这个的。", ex: "Watching you on stage — you were born for this." },
    ],
  },
  {
    cat: "吐槽与抱怨",
    items: [
      { en: "It's driving me crazy.", zh: "快把我逼疯了。", ex: "The neighbor's dog barks at 6 a.m. sharp — it's driving me crazy." },
      { en: "What's the deal with...?", zh: "……到底是怎么回事？", ex: "What's the deal with the elevator being 'under maintenance' for a month?" },
      { en: "I've had it up to here.", zh: "我已经忍无可忍了。", ex: "Another last-minute change? I've had it up to here." },
      { en: "It's not rocket science.", zh: "这又不是造火箭（没那么难）。", ex: "Just reply to the email — it's not rocket science." },
      { en: "Don't get me started on...", zh: "别让我吐槽……（一说就停不下来）", ex: "The food was fine, but don't get me started on the service." },
      { en: "Of course, today of all days.", zh: "偏偏是今天（真会挑日子）。", ex: "The printer died — of course, today of all days, right before the deadline." },
      { en: "That's the last straw.", zh: "这是压垮我的最后一根稻草。", ex: "They cancelled on me again — that's the last straw." },
      { en: "It's a rip-off.", zh: "太宰人了。", ex: "Sixty yuan for a tiny coffee? What a rip-off." },
      { en: "Typical.", zh: "意料之中（讽刺）。", ex: "He took the credit again? Typical." },
      { en: "I can't be bothered.", zh: "我懒得弄了。", ex: "I should cook, but honestly, I can't be bothered tonight." },
      { en: "It defeats the purpose.", zh: "这不是本末倒置吗。", ex: "Driving to the gym to walk on a treadmill kind of defeats the purpose." },
      { en: "Story of my life.", zh: "我的人生常态（自嘲）。", ex: "The bus left right as I got there — story of my life." },
    ],
  },
];

// ============ 填充词列表 ============
const FILLERS = ["um", "uh", "er", "erm", "hmm", "you know", "i mean", "like"];
